spring:
    application:
        name: gate-demo-client

server:
    port: 8764

eureka:
    instance:
        statusPageUrlPath: ${management.context-path}/info
        healthCheckUrlPath: ${management.context-path}/health
        preferIpAddress: true
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

gate:
  client:
    clientId: gate-demo-client
    secret: test
    authHeader: access-token
    authHost: http://localhost:8762/api/authen
    tokenHead: ApiGateToken

feign:
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true